version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/hipaa_db
      - ENVIRONMENT=development
      - JWT_SECRET=your-secret-key-change-in-production
      - LOG_LEVEL=INFO
    depends_on:
      - db
    volumes:
      - ./src:/app/src:ro
    networks:
      - hipaa-network
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=hipaa_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hipaa-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hipaa-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  hipaa-network:
    driver: bridge